"""Create new tables and apply changes

Revision ID: 28bcc59ad8a7
Revises: a3ae407230f6
Create Date: 2025-04-25 03:24:46.572365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28bcc59ad8a7'
down_revision = 'a3ae407230f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_health_program',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('health_program_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['health_program_id'], ['health_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'health_program_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_health_program')
    op.drop_table('clients')
    # ### end Alembic commands ###
